# log config
#log_wandb: true

# Hyperparameter config
n_layers: 4
n_heads: 4

# dataset config
data_path: ./training_data/
dataset: hm
field_separator: "\t"
USER_ID_FIELD: customer_id
ITEM_ID_FIELD: article_id
RATING_FIELD: ~
TIME_FIELD: t_dat
show_progress: true

load_col:
    inter: [customer_id, article_id, t_dat]
    user: [customer_id]
    item: [article_id]

# model config
epochs: 12
train_batch_size: 300
eval_batch_size: 300
learning_rate: 0.01
user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
filter_inter_by_user_or_item: false
neg_sampling:
    uniform: 1
eval_args:
    split: {'RS': [4, 1, 1]}
    group_by: None
    order: TO
    mode: uni50
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk: 12
valid_metric: MAP@12
